#- name: Download mysql package
#  get_url: url=http://download.softagency.net/MySQL/Downloads/MySQL-5.5/mysql-{{ mysql_version }}.tar.gz dest=/tmp/mysql-{{ mysql_version }}.tar.gz sha256sum={{ mysql_sha256sum}}
- name: Copy libiconv package
  copy: src=libiconv-{{ libiconv_version }}.tar.gz dest=/tmp/libiconv-{{ libiconv_version }}.tar.gz

- name: Extrect archive
  command: chdir=/tmp/ /bin/tar xvf libiconv-{{ libiconv_version }}.tar.gz creates=/tmp/libiconv-{{ libiconv_version }}

- name: Configure
  command: chdir=/tmp/libiconv-{{ libiconv_version }} ./configure --prefix=/usr/local

- name: Make
  command: chdir=/tmp/libiconv-{{ libiconv_version }} make -j4

- name: Make install
  command: chdir=/tmp/libiconv-{{ libiconv_version }} make install


