---
- hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:

    - name: del user
      # Linux passwd use SHA512
      # from passlib.hash import sha512_crypt
      # sha512_crypt.encrypt('passwdstr')
      # Options: name password uid group shell generate_ssh_key ssh_key_type ssh_key_comment state remove
      user: name={{ username }} state=absent
