---
- name: Install development tools
  yum: name="@Development tools" state=present

- name: Install extra libs
  yum: name={{ item }} state=present
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
